### PR TITLE
Synchronized animation

### LINKED ISSUE #48: Synchronize the Animation
Synchronize the Cursor and fill animation on the home page

ras

### PR DESCRIPTION
**Pull request by Virtual4087**
Fixes #48 

ezgif-1-9c64fe6171

As you can see, I've reduced coverage area of the cursor. It was previously set to reach a bit further than the text so I fixed that and synchronized the animation as well. If that wasn't what you intended on doing, let me know and I'll fix it.

### CODE REVIEW

**Comment by IbraheemHaseeb7** [comment]
Hey @Virtual4087 

That looks pretty good. There is a property in CSS where you can use steps in animation timing function....that would actually give it a look of typing.....perhaps we can try that. Otherwise looks really good

**Comment by Virtual4087** [comment]
@IbraheemHaseeb7 sorry but something came up and I was busy for the last few days. Can I know which CSS property are you talking about? I'm not very good at CSS but I could give it a try.

**Comment by IbraheemHaseeb7** [comment]
in css you explore the `animation-timing-function` and set it `steps` function. Explore this and you will get it what I am tryna say....good luck 🙌

**Comment by saadman-galib** [comment]
@IbraheemHaseeb7 I have set it to steps function. would you please check my pull request?

**Pull request merged**
