### PR TITLE
Fix Contributors Page contributors container padding

### PR DESCRIPTION
**Pull request by saadman-galib**
Add padding to the contributors page contributors container. #77 #78

### CODE REVIEW

**Comment by IbraheemHaseeb7** [comment]
can you make it `padding: 15px 0` so it does not add padding along the x-axis?

Submit your PR....the other PR was not working so I am going to accept yours now.

**Comment by IbraheemHaseeb7** [comment]
nevermind...someone already submitted PR. Better luck next time

**Comment by saadman-galib** [comment]
yeah sure. I have done that. Can you pls review my pull request?

**Comment by IbraheemHaseeb7** [comment]
sorry but someone's PR for merged before yours. Anyways thank you so much for the contributions. We are changing the rules for contribution soon for fairness to everyone.

**Pull request closed without merging**
