### PR TITLE
Shubhusion/issue10

### LINKED ISSUE #10: Clean the HTML & CSS code in repo use universal styling techniques and naming schemes for files.

### PR DESCRIPTION
**Pull request by shubhusion**
fixes #10

### CODE REVIEW

**Comment by shubhusion** [comment]
@imrtls00 @code-reaper08 @IbraheemHaseeb7 @DevWeb13 can anyone review my PR.

**Comment by IbraheemHaseeb7** [comment]
hey @shubhusion 

Thank you so much for the PR. Unfortunately your PR contains a lot of previous code which will eliminate our new iterations. If you can address them I will merge it immediately

**Comment by shubhusion** [comment]
I will again make the PR.

**Comment by IbraheemHaseeb7** [comment]
Okay great waiting on it 🙌

**Pull request closed without merging**
