### PR TITLE
 cordinators to coordinators

### PR DESCRIPTION
**Pull request by NishantKuthe**

### CODE REVIEW

**Comment by IbraheemHaseeb7** [comment]
@NishantKuthe kindly make it Co-ordinators and we will merge it

**Comment by NishantKuthe** [comment]
i did changes as you ask and also solved the #8 problem in this pr "fixed grid size of card"

**Comment by bbhupen** [comment]
image


Clicking Coordinators doesn't display coordinators anymore

**Comment by NishantKuthe** [comment]
> image
> 
> Clicking Coordinators doesn't display coordinators anymore

Ok    I'll try to fixed that issue

**Comment by NishantKuthe** [comment]
done

**Pull request merged**
